version: '3.10'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      ENV: production

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    environment:
      ENV: production
      HUPRES_GOOGLE_0AUTH_CLIENT_ID: ${HUPRES_GOOGLE_0AUTH_CLIENT_ID}
      HUPRES_GOOGLE_0AUTH_CLIENT_SECRET: ${HUPRES_GOOGLE_0AUTH_CLIENT_SECRET}
      HUPRES_SECRET_SESSION_KEY: ${HUPRES_SECRET_SESSION_KEY}
      HUPRES_OPENAI_API_KEY: ${HUPRES_OPENAI_API_KEY}
      HUPRES_POSTGRES_USERNAME: ${HUPRES_POSTGRES_USERNAME}
      HUPRES_POSTGRES_PASSWORD: ${HUPRES_POSTGRES_PASSWORD}
      HUPRES_POSTGRES_HOSTNAME: ${HUPRES_POSTGRES_HOSTNAME}
      HUPRES_POSTGRES_PORT: ${HUPRES_POSTGRES_PORT}
      HUPRES_POSTGRES_DATABASE_NAME: ${HUPRES_POSTGRES_DATABASE_NAME}
