# Build stage
FROM node:16 as build

# Define build stage environment variables
ARG HUPRES_ENV
ARG HUPRES_APP_PORT
ARG HUPRES_PROD_HOSTNAME
ENV HUPRES_ENV=${HUPRES_ENV}
ENV HUPRES_APP_PORT=${HUPRES_APP_PORT}
ENV HUPRES_PROD_HOSTNAME=${HUPRES_PROD_HOSTNAME}

WORKDIR /app
COPY frontend/package*.json ./
COPY frontend/yarn.lock ./
RUN yarn install
COPY frontend/ .
RUN yarn build

# Serve stage
FROM nginx:stable-alpine

# Copy nginx config
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./nginx-config /etc/nginx/conf.d

# Copy SSL certificates for nginx
COPY secrets/certificates/hupres_origin.pem /etc/ssl/certs/hupres_origin.pem
COPY secrets/certificates/hupres_private.key /etc/ssl/private/hupres_private.key

EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
