# Build stage
FROM node:16 as build
WORKDIR /app
COPY frontend/package*.json ./
COPY frontend/yarn.lock ./
RUN yarn install
COPY frontend/ .
RUN yarn build

# Serve stage
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./nginx-config /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
