version: '3.10'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
      args:
        - HUPRES_ENV="${HUPRES_ENV}"
        - HUPRES_APP_PORT="${HUPRES_APP_PORT}"
        - HUPRES_PROD_HOSTNAME="${HUPRES_PROD_HOSTNAME}"
    image: hupres/hupres-monorepo:frontend
    ports:
      - "${HUPRES_APP_PORT}:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: hupres/hupres-monorepo:backend
    ports:
      - "8000:8000"
    environment:
      HUPRES_ENV: ${HUPRES_ENV}
      HUPRES_APP_PORT: ${HUPRES_APP_PORT}
      HUPRES_PROD_HOSTNAME: ${HUPRES_PROD_HOSTNAME}
      HUPRES_GOOGLE_0AUTH_CLIENT_ID: ${HUPRES_GOOGLE_0AUTH_CLIENT_ID}
      HUPRES_GOOGLE_0AUTH_CLIENT_SECRET: ${HUPRES_GOOGLE_0AUTH_CLIENT_SECRET}
      HUPRES_SECRET_SESSION_KEY: ${HUPRES_SECRET_SESSION_KEY}
      HUPRES_OPENAI_API_KEY: ${HUPRES_OPENAI_API_KEY}
      HUPRES_POSTGRES_USERNAME: ${HUPRES_POSTGRES_USERNAME}
      HUPRES_POSTGRES_PASSWORD: ${HUPRES_POSTGRES_PASSWORD}
      HUPRES_POSTGRES_HOSTNAME: ${HUPRES_POSTGRES_HOSTNAME}
      HUPRES_POSTGRES_PORT: ${HUPRES_POSTGRES_PORT}
      HUPRES_POSTGRES_DATABASE_NAME: ${HUPRES_POSTGRES_DATABASE_NAME}
