"""Add created_at and updated_at

Revision ID: 49ae8766f858
Revises: 367b0565ac08
Create Date: 2023-11-15 20:38:41.275014

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision: str = '49ae8766f858'
down_revision: Union[str, None] = '367b0565ac08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tables = ['users', 'quizzes', 'quiz_answers', 'quiz_free_form_questions',
              'quiz_questions', 'quiz_summaries']

    for table in tables:
        op.add_column(table, sa.Column('created_at', sa.DateTime, server_default=expression.func.now(), nullable=False))
        op.add_column(table, sa.Column('updated_at', sa.DateTime, server_default=expression.func.now(), onupdate=expression.func.now(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tables = ['users', 'quizzes', 'quiz_answers', 'quiz_free_form_questions',
              'quiz_questions', 'quiz_summaries']

    for table in tables:
        op.drop_column(table, 'created_at')
        op.drop_column(table, 'updated_at')
    # ### end Alembic commands ###
